### ISSUE TITLE
Newbie in Need of assistance - The conditional check 'use_local_repository|bool' failed

### ISSUE THREAD

**Issue by pr2627** [Keyfactor/ansible-ejbca-signserver-playbooks#34]
Running the EJBCA deployCeNode.yml on a localhost and I am getting the following error:

TASK [ansible-ejbca-prep : Upload and unpack Apache ant from Ansible controller] **********************************************************************fatal: [localhost]: FAILED! => 
  msg: |-
    The conditional check 'use_local_repository|bool' failed. The error was: error while evaluating conditional (use_local_repository|bool): 'use_local_repository' is undefined
  
    The error appears to be in '/root/primekey/ansible_ejbca_signsrv/roles/ansible-ejbca-prep/tasks/install.yml': line 44, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
        - name: Upload and unpack Apache ant from Ansible controller
         ^ here

The offending section appears to be the following:

- name: Ant staging
  block:

    - name: Upload and unpack Apache ant from Ansible controller
      unarchive:
        src: "{{ apache_ant_remote_dir }}"
        dest: "{{ ejbca_root_dir }}"
      register: unpacked_local_ant
      when:
        - use_local_repository|bool

   Any assistance in resolving  this issue would be appreciated.

   Thanks

**Comment by jtgarner-keyfactor** [comment]
In the [group_vars/ceServers.yml](https://github.com/Keyfactor/ansible-ejbca-signserver-playbooks/blob/master/ansible_ejbca_signsrv/group_vars/ceServers.yml) on line:28 there is a default variable `use_local_repository: false`

The ceServers variable file is included when you set your play limit to include ceServers. Can you confirm the line still exists, is not commented out, and the command you executed to run the play looks similar to `ansible-playbook -i inventory -l ceServers,ce01 deployCeNode.yml`

**Comment by pr2627** [comment]
[jtgarner-keyfactor](https://github.com/jtgarner-keyfactor),
  I apologize as I have been working on another project.  I will respond shortly.  Thank you in advance for your response.

**Comment by svenska-primekey** [comment]
No response in a few months.
