### ISSUE TITLE
Support for Debian based linux Distribution

### ISSUE THREAD

**Issue by JeromeBollinger** [Keyfactor/ansible-ejbca-signserver-playbooks#41]
Is it already possible to run the ansible playbooks on debian based linux distribution?
It fails on the ansible-role-mariadb part, since there is no Debian.yml file in vars directory.
However, I see nothing in the documentation stating, that it only would run on Fedora or RedHat distros.
Is there a easy way to modify the files to support debian or could you maybe add a list of supported distributions?
I rarely use 3rd party ansible scripts and thus do not know how people usually manage compatibility.

**Comment by svenska-primekey** [comment]
No movement on this issue.
