### ISSUE TITLE
Thales HSM with the Community Edition Support

### ISSUE THREAD

**Issue by walshg3** [Keyfactor/ansible-ejbca-signserver-playbooks#42]
Hello,

I am curious if I can use a Thales T2000 with EJBCA Community Edition. When trying to install with the 
`ansible-playbook -i inventory -l ce01 deployCeNode.yml --ask-become-pass` playbook and getting an error saying hsmusers is undefined. 
![image](https://github.com/Keyfactor/ansible-ejbca-signserver-playbooks/assets/26581084/a0b3ea0d-9185-4ab2-bc27-52c05bb101b0)

I don't see any documentation to support the hsmusers variable / where it should go. I'm guessing i'm missing some important documentation or Thales HSM isn't supported with the community edition install. 

Thank you for your time.

**Comment by danner26** [comment]
+1 this would be useful

**Comment by svenska-primekey** [comment]
The luna client was never flushed out with all the steps to install the client or use it. It was a place holder that needs to be completed. If you would like to contribute a role update for that and submit a pull request that would be great.

**Comment by svenska-primekey** [comment]
No movement on this issue. Closing for now.
