### ISSUE TITLE
allow username and password while generating certificate from ejbca

### ISSUE THREAD

**Issue by adityajoshi12** [Keyfactor/ansible-ejbca-signserver-playbooks#55]
**Is your feature request related to a problem or specific use case? Please describe.**

The `ejbca_certificate` module is an essential tool for managing EJBCA certificates using Ansible. However, the current implementation of the module requires the username and password to be hardcoded within the module itself. This restricts the user from providing custom credentials, potentially leading to security vulnerabilities and limitations in flexibility.

**Describe the solution you'd like**
the `ejbca_certificate` module be updated to allow users to pass custom username and password parameters. This can be achieved by modifying the module to accept these parameters as variables, rather than hardcoding them within the module. I have raised PR #56 for the changes. 

**Product deployment**
Please complete the following information:
 - Deployment format: [e.g. software, container]
 - Version [e.g. 8.0.0]

**Additional context**

**Comment by svenska-primekey** [comment]
PR merged for this feature request.
